/**
 * 错误码常量定义
 * 统一管理应用中使用的错误码
 */

module.exports = {
  // HTTP 状态码
  HTTP_OK: 200,
  HTTP_BAD_REQUEST: 400,
  HTTP_UNAUTHORIZED: 401,
  HTTP_FORBIDDEN: 403,
  HTTP_NOT_FOUND: 404,
  HTTP_INTERNAL_SERVER_ERROR: 500,
  HTTP_BAD_GATEWAY: 502,
  HTTP_SERVICE_UNAVAILABLE: 503,
  
  // 业务错误码
  BUSINESS_SUCCESS: 0,
  BUSINESS_PARAM_ERROR: 1001,
  BUSINESS_DATA_NOT_FOUND: 1002,
  BUSINESS_DATA_EXISTS: 1003,
  BUSINESS_OPERATION_FAILED: 1004,
  
  // 网络错误
  NETWORK_TIMEOUT: -1,
  NETWORK_DISCONNECT: -2,
  NETWORK_UNKNOWN: -3,
  
  // 数据解析错误
  PARSE_ERROR: 2001,
  PARSE_EMPTY_DATA: 2002,
  PARSE_INVALID_FORMAT: 2003
}
